# Generated by Django 2.1.4 on 2018-12-22 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Habit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('habit_name', models.CharField(max_length=200)),
                ('start_date', models.DateTimeField(verbose_name='date published')),
                ('habit_desc', models.TextField()),
                ('habit_priority', models.IntegerField()),
            ],
        ),
    ]
