# Generated by Django 2.1.4 on 2019-01-05 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0003_auto_20190105_0456'),
    ]

    operations = [
        migrations.AddField(
            model_name='habit',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
