# Generated by Django 2.1.4 on 2019-01-06 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0005_auto_20190105_2030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='habit_priority',
            field=models.IntegerField(choices=[(1, 'High'), (2, 'Medium'), (3, 'Low')], default=2),
        ),
    ]
