# Generated by Django 2.1.4 on 2019-01-06 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0006_auto_20190105_2035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='habit_priority',
            field=models.IntegerField(),
        ),
    ]
