# Generated by Django 2.1.4 on 2019-01-08 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0008_habit_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='habit',
            name='last_update',
            field=models.DateField(null=True),
        ),
    ]
