# Generated by Django 2.1.4 on 2019-01-08 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0010_auto_20190107_2014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='habit_priority',
            field=models.IntegerField(choices=[(0, 'Low'), (1, 'Normal'), (2, 'High')], default=1),
        ),
    ]
