# Generated by Django 2.1.4 on 2019-01-09 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0011_auto_20190107_2042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='habit_name',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
