# Generated by Django 2.1.5 on 2019-01-10 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0013_auto_20190109_1308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='habit_desc',
            field=models.TextField(blank=True),
        ),
    ]
