# Generated by Django 2.1.5 on 2019-01-13 05:47

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0016_habit_trackeddays'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='habit',
            name='trackedDays',
        ),
        migrations.AddField(
            model_name='habit',
            name='tracked_days',
            field=multiselectfield.db.fields.MultiSelectField(choices=[(2, 'Wednesday'), (0, 'Monday'), (4, 'Friday'), (6, 'Sunday'), (3, 'Thursday'), (1, 'Tuesdsay'), (5, 'Saturday')], max_length=13, null=True),
        ),
    ]
