# Generated by Django 2.1.5 on 2019-01-13 05:48

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0017_auto_20190112_2147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='tracked_days',
            field=multiselectfield.db.fields.MultiSelectField(choices=[(0, 'Monday'), (1, 'Tuesdsay'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], max_length=13, null=True),
        ),
    ]
