# Generated by Django 2.1.5 on 2019-01-13 21:35

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0019_auto_20190113_1334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='tracked_days',
            field=multiselectfield.db.fields.MultiSelectField(choices=[(0, 'Monday'), (1, 'Tuesdsay'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], default=['0', '1', '2', '3', '4', '5', '6'], max_length=13),
        ),
    ]
