# Generated by Django 2.1.5 on 2019-01-16 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0023_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='status',
            field=models.CharField(choices=[('perfect', 'Perfect'), ('none', 'None'), ('partial', 'Partial')], max_length=10),
        ),
    ]
