# Generated by Django 2.1.5 on 2019-01-16 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0024_auto_20190115_1659'),
    ]

    operations = [
        migrations.RenameField(
            model_name='habit',
            old_name='habit_desc',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='habit',
            old_name='habit_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='habit',
            old_name='habit_priority',
            new_name='priority',
        ),
        migrations.AlterField(
            model_name='event',
            name='status',
            field=models.CharField(max_length=10),
        ),
    ]
